### ISSUE TITLE
Brief Texture change into Fiery block

### ISSUE THREAD

**Issue by VallenFrostweaver** [Darkhax-Minecraft/GYTH#21]
When placing the tanks I sometimes get a random texture change into a lit on fire glass block for a few moments and then it goes away and reverts to the proper block.
version 2.1.36
Forge 14.23.5.2768
![gyth error](https://user-images.githubusercontent.com/13642054/47667527-19dc8c00-db9e-11e8-97c3-1abfebcee8e0.png)

**Comment by Darkhax** [comment]
The fire texture is shown when the tier of the tank isn't known to the client. This normally happens when you have a tank tier that was removed, or the data hasn't synced with the client yet. This can happen if the client is slow to receive an update packet from the server. If you're playing on a server that may be cause.

**Comment by VallenFrostweaver** [comment]
Single player, no server. It lasted for 2-4 seconds and happened twice while placing about 30-50 different tanks

**Comment by Darkhax** [comment]
I really can't figure out a solution to this issue, other than the one I provided earlier. Keep in mind that the server is running in background while playing single player, and the data syncs are not instantaneous. The fire texture is used when the client side block doesn't have any tier data applied to it. There is a similar "bug" in vanilla where breaking sunflowers can cause the top block to look like a different flower for a few seconds. If you have any other info that can be used to fix this please let me know and I can re-open the issue.
